import type { Metadata } from "next";
import { Dosis } from "next/font/google";
import "./globals.css";
import Header from "./header"

const dosisLight = Dosis({
  subsets: ['latin'],
  weight: '500',
  variable: '--font-dosis',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${dosisLight.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <div className="flex flex-col flex-1 bg-zinc-50 font-sans dark:bg-black">
          <main className="px-100 py-25">
            <Header />
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
